name: "create-pull-request"
description: "Create pull request"
author: "Filip Jenik"
icon: "bookmark"
color: "yellow"
inputs:
  repo-token:
    description: "The GITHUB_TOKEN secret"
    required: true
  source-branch:
    description: "Source branch"
    required: false
    default: "develop"
  target-branch:
    description: "Target branch"
    required: false
    default: "master"
  pr-title:
    description: "Pull request title"
    required: false
    default: "Merge master to develop"
  pr-body:
    description: "Pull request body"
    required: false
    default: null
  pr-reviewers:
    description: "List of reviewers separated with a comma"
    required: false
    default: null
  pr-assignees:
    description: "List of assignees separated with a comma"
    required: false
    default: null
  pr-labels:
    description: "List of labels separated with a comma"
    required: false
    default: null

runs:
  using: "node12"
  main: "dist/index.js"
